<?php
namespace APP\CORE\ENUM;

enum ClassKey : string{
    case DATABASE = 'DATABASE';
    case SESSION = 'SESSION';
    
    case COMPTE_REPOSITOTY = 'COMPTE_REPOSITOTY';
    case UTILISATEUR_REPOSITOTY = 'UTILISATEUR_REPOSITOTY';
    case TRANSACTION_REPOSITOTY = 'TRANSACTION_REPOSITOTY';

    case COMPTE_SERVICE = 'COMPTE_SERVICE';
    case UTILISATEUR_SERVICE = 'UTILISATEUR_SERVICE';
    case SECURITY_SERVICE = 'SECURITY_SERVICE';
    case TRANSACTION_SERVICE = 'TRANSACTION_SERVICE';

    case UTILISATEUR_CONTROLLER = 'UTILISATEUR_CONTROLLER';
    case COMPTE_CONTROLLER = 'COMPTE_CONTROLLER';
    case SECURITY_CONTROLLER = 'SECURITY_CONTROLLER';
    case TRANSACTION_CONTROLLER = 'TRANSACTION_CONTROLLER';


    case AUTH_MIDDLEWARE = 'AUTH_MIDDLEWARE';
}